#!/bin/sh

export EDITOR="emacsclient -t"
export VISUAL="emacsclient -c"
export MP_FULLNAME="<xxx>"

alias e="$EDITOR"
alias ev="$VISUAL"
alias o=xdg-open
alias l=exa
alias t=trash-put
alias ll="exa -l"
alias lg="exa --long --git"
